### ISSUE TITLE
Failed with version 1.21

### ISSUE THREAD

**Issue by Mundo-Minecraft** [PaintballWarEdition/PaintballLegacy#4]
Hello, unfortunately the plugin does not work with version 1.21. Indicates the following when booting in the log: 

https://pastebin.com/uzfHWhrq

I use the latest version of paper 1.21, I also tried spigot.

Thank you and greetings.

**Comment by blablubbabc** [comment]
I uploaded an update to dev.bukkit.org that should include the fix for 1.21+ (pending approval)
