### ISSUE TITLE
How use the plugin

### ISSUE THREAD

**Issue by Boubame** [PaintballWarEdition/PaintballLegacy#6]
Hello, I don't know how to write directly to someone so I'm here. How can I download the file in .jar to use it as a plugin?
Its the best paintball plugin but i wasn't able to get the plugin (.jar file) for a new version (1.21) 
https://dev.bukkit.org/projects/paintball_pure_war
Thanks in advance

**Comment by Boubame** [comment]
so if u have a .jar plugin or the way to use the code in my server i'll be very happy :)

**Comment by datatags** [comment]
There isn't a published release of the latest commit at the moment, you'll have to build it yourself. You can do so by cloning the repository and using `./gradlew build`, and the result should show up in the folder `build/libs/`

**Comment by Boubame** [comment]
Being just a beginner, what is the deposit?

**Comment by blablubbabc** [comment]
I uploaded an update to dev.bukkit.org (currently pending approval, should show up in the next few days)
